### ISSUE TITLE
config file bug?

### ISSUE THREAD

**Issue by rafa-cxg** [ChCh1999/RTPB#2]
Hi! when I run the code with script , I find the following  key is not shown in default.py, thus caused failure. 
https://github.com/ChCh1999/RTPB/blob/4f72279d4b63f8818999678507e4f0bafc6cb1b4/configs/e2e_relation_X_101_32_8_FPN_1x_trans_predcls.yaml#L91

**Comment by ChCh1999** [comment]
It's a bug and we will fix it. You can just delete the following code block.
https://github.com/ChCh1999/RTPB/blob/4f72279d4b63f8818999678507e4f0bafc6cb1b4/configs/e2e_relation_X_101_32_8_FPN_1x_trans_predcls.yaml#L91-L102

**Comment by rafa-cxg** [comment]
Thanks!
