### ISSUE TITLE
These parameters are missing in the config files

### ISSUE THREAD

**Issue by hszhoushen** [ChCh1999/RTPB#3]
e.g., these parameters are not exists in e2e_relation_X_101_32_8_FPN_1x_trans_predcls.yaml

MODEL.ROI_RELATION_HEAD.DUAL_TRANS.USE_GRAPH_ENCODE True MODEL.ROI_RELATION_HEAD.DUAL_TRANS.GRAPH_ENCODE_STRATEGY trans

**Comment by ChCh1999** [comment]
They are initialized in the  [config file](https://github.com/ChCh1999/RTPB/blob/1066a3bfe4fe1b41eff74fd152936880302a60a2/maskrcnn_benchmark/config/defaults.py), e.g. [MODEL.ROI_RELATION_HEAD.DUAL_TRANS.GRAPH_ENCODE_STRATEGY trans](https://github.com/ChCh1999/RTPB/blob/1066a3bfe4fe1b41eff74fd152936880302a60a2/maskrcnn_benchmark/config/defaults.py#L321)
