### ISSUE TITLE
Hello, what is the pytorch and cuda environment of RTPB?

### ISSUE THREAD

**Issue by hekaijie123** [ChCh1999/RTPB#6]
Hello, what is the pytorch and cuda environment of RTPB? I can't compile successfully while running python setup.py build develop, my environment is pytorch 1.12 and cuda11.3 @ChCh1999

**Comment by ChCh1999** [comment]
My environment is PyTorch 1.10 and cuda11.1. Please provide more detail about your problem so I can determine what happened to you.
