### ISSUE TITLE
Could not find the vb implementation

### ISSUE THREAD

**Issue by PommesPeter** [ChCh1999/RTPB#7]
Hi,
when I try to run the script [DT_base_vb.sh](https://github.com/ChCh1999/RTPB/blob/main/scripts/predcls/DT_base_vb.sh), it shows:
![40a3432163874b595d1ca2286513446](https://user-images.githubusercontent.com/54879512/202380711-c3cfa431-8410-4bd4-8cd3-dcfff7e35260.png)

it means that it could not find the key "pair_count_bias". after checking the code, I found that there are no conditions equaling "pair_count_bias" in [bias_module.py](https://github.com/ChCh1999/RTPB/blob/1f63b708118b52efe58806ca05291d35208af7a6/maskrcnn_benchmark/modeling/roi_heads/relation_head/modules/bias_module.py#L131) which is using for forwarding process. How do I run the [DT_base_vb.sh](https://github.com/ChCh1999/RTPB/blob/main/scripts/predcls/DT_base_vb.sh) scripts in your code?

**Comment by ChCh1999** [comment]
Sorry about our mistake, I've updated the related code.

**Comment by PommesPeter** [comment]
> Sorry about our mistake, I've updated the related code.

I got it, thank you.
